version: "3.3"

services:

  portainer:
    image: portainer/portainer
    ports:
      - "9999:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/portainer_data:/data
    command: --no-auth
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '1000mb'
        reservations:
          cpus: '0.1'
          memory: '250mb'

  influxdb:
    image: influxdb:1.7.6
    ports:
      - 8086:8086
    volumes:
      - /var/lib/influxdb
    environment:
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: pass
      INFLUXDB_DB: boot
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '1000mb'
        reservations:
          cpus: '0.1'
          memory: '250mb'
  grafana:
    image: grafana/grafana:6.1.6
    ports:
      - 3000:3000
    volumes:
      - /var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '1000mb'
        reservations:
          cpus: '0.1'
          memory: '250mb'
    depends_on:
      - influxdb

  discovery-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: thiagolocatelli/discovery-service:0.0.1-SNAPSHOT
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://127.0.0.1:8888/actuator/health -O /dev/null"]
      interval: 30s
      timeout: 1s
      retries: 4
    ports:
      - "8888:8888/tcp"
    deploy:
      replicas: 1

  api-gateway:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: thiagolocatelli/api-gateway:0.0.1-SNAPSHOT
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://127.0.0.1:9000/actuator/health -O /dev/null"]
      interval: 30s
      timeout: 1s
      retries: 4
    ports:
      - "9000:9000/tcp"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '1000mb'
        reservations:
          cpus: '0.1'
          memory: '250mb'
    depends_on:
      - discovery-service

  proxy-gateway:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: thiagolocatelli/proxy-gateway:0.0.1-SNAPSHOT
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://127.0.0.1:9001/actuator/health -O /dev/null"]
      interval: 30s
      timeout: 1s
      retries: 4
    ports:
      - "9001:9001/tcp"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '1000mb'
        reservations:
          cpus: '0.1'
          memory: '250mb'
    depends_on:
      - discovery-service

  user-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: thiagolocatelli/user-service:0.0.1-SNAPSHOT
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://127.0.0.1:8081/actuator/health -O /dev/null"]
      interval: 30s
      timeout: 1s
      retries: 4
    ports:
      - "8081:8081/tcp"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '1000mb'
          cpus: '0.5'
        reservations:
          cpus: '0.1'
          memory: '250mb'
    depends_on:
      - user-db
      - discovery-service

  movie-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: thiagolocatelli/movie-service:0.0.1-SNAPSHOT
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://127.0.0.1:8082/actuator/health -O /dev/null"]
      interval: 30s
      timeout: 1s
      retries: 4
    ports:
      - "8082:8082/tcp"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '1000mb'
          cpus: '0.5'
        reservations:
          cpus: '0.1'
          memory: '250mb'
    depends_on:
      - movie-db
      - discovery-service

  rating-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: thiagolocatelli/rating-service:0.0.1-SNAPSHOT
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://127.0.0.1:8083/actuator/health -O /dev/null"]
      interval: 30s
      timeout: 1s
      retries: 4
    ports:
      - "8083:8083/tcp"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '1000mb'
          cpus: '0.5'
        reservations:
          cpus: '0.1'
          memory: '250mb'
    depends_on:
      - rating-db
      - discovery-service

  cart-service:
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: thiagolocatelli/cart-service:0.0.1-SNAPSHOT
    healthcheck:
      test: ["CMD-SHELL", "wget -q http://127.0.0.1:8084/actuator/health -O /dev/null"]
      interval: 30s
      timeout: 1s
      retries: 4
    ports:
      - "8084:8084/tcp"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '1000mb'
          cpus: '0.5'
        reservations:
          cpus: '0.1'
          memory: '250mb'
    depends_on:
       - cart-db
       - discovery-service

  user-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432/tcp"
    deploy:
      replicas: 1

  movie-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432/tcp"
    deploy:
      replicas: 1

  cart-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432/tcp"
    deploy:
      replicas: 1

  rating-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432/tcp"
    deploy:
      replicas: 1
